# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a11d0f7a112854d0173df77ea439e519db5be57cc6649ce62c0e891a977c0607ffbaa241753882b0d935223b991c9b55692b9d19c7a90ba844e776c9f37d355d

test:
  secret_key_base: 7e68584795cc00b084ebb9bda3e028331639391a15d61cd51def5f8c8d9cfd79e17a7c9021386e5e198bd76f0bead8c9fbe02ec8348fc0281a6be2b4a9428e7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
